# Generated by Django 2.2.1 on 2019-10-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackGround', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('pthone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(default=1)),
            ],
        ),
    ]
