# Generated by Django 2.2.1 on 2019-10-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackGround', '0003_auto_20191006_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='BackGround.LoginUser', verbose_name='文章发表者'),
        ),
    ]
